# Generated by Django 4.2.3 on 2023-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_items_alter_cart_user_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(blank=True, default='dict'),
        ),
    ]
